import { Preset } from "./types";

export const PRESETS: Preset[] = [
  {
    id: "pop-indonesia-klasik",
    name: "Lagu Pop Indonesia Klasik",
    iconName: "Heart",
    genre: "Pop Indonesia Klasik, Slow Rock, Balada Pop 90's",
    mood: "Heartfelt, Sweet, Nostalgic, Loving, Expressive",
    tempo: "72 BPM",
    key: "C / G (Bright and comfortable for vocals)",
    vocalStyle: "Clear Male/Female Vocal, Tender, Intimate, Direct Emotion, Clean Vibrato, Chest Voice with Soft Nuance",
    lyricLanguage: "Bahasa Indonesia Sederhana, Langsung (Aku, Kau, Dirimu, Kasih, Sayang, Pola: Kau hadir... / Kasih, genggamlah... / Betapa aku...)",
    storyFlow: "Verse 1A (Perkenalan & Cinta Awal: KAU hadir) → Verse 1B (Perkembangan Cinta: Mata, Senyum, Sentuhan) → Pre-Chorus (Eskalasi) → Chorus A (Hook Utama: Kasih/Sayang + Pengakuan Cinta) → Chorus B (Variasi Hook) → Verse 3 (Penguatan Rasa) → Bridge (Janji & Kesetiaan) → Final Chorus (Klimaks) → Outro (Penutup Manis + Vocalization)",
    description: "Gaya lagu cinta Indonesia klasik dengan bahasa langsung, sederhana, komunikatif, dan hook yang mudah diingat.",
  },
  {
    id: "balada-melayu-dangdut-slow",
    name: "Balada Melayu & Dangdut Slow (Dramatis)",
    iconName: "HeartCrack",
    genre: "Balada Melayu, Dangdut Slow, Slow Rock Melayu 90's",
    mood: "Deeply Emotional, Heartfelt, Melancholic, Dramatic, Poetic, Hope in Pain",
    tempo: "72 BPM",
    key: "Am / Dm (minor key, highly emotional with room for cengkok)",
    vocalStyle: "Clear Emotional Vocal, Deep Feeling, Soft Cengkok / Vibrato, Chest Voice with Holding Notes",
    lyricLanguage: "Natural Poetic Indonesian, Dual Metaphors (Cinta & Luka), Story Arc (Cinta → Luka → Menerima → Harapan → Bahagia → Luka Membekas)",
    storyFlow: "Verse 1A (Pembukaan Cinta & Metafora Bunga) → Verse 1B (Citraan Luka & Darah Jiwa) → Pre-Chorus (Eskalasi) → Chorus 1A (Pernyataan Utama) → Chorus 1B (Pertanyaan Emosional & Kamar Gelap) → Bridge (Penerimaan Luka & Harapan Sinar Suria) → Outro (Filosofi & Kebahagiaan di Sebalik Duka) → Reprise (Penutup Luka Realistis)",
    description: "Struktur balada Melayu/Dangdut slow dengan kurva emosi dramatis: CINTA → LUKA → PERTANYAAN → PENERIMAAN → HARAPAN → BAHAGIA → LUKA YANG MASIH TERSISA.",
  },
  {
    id: "slow-rock-melayu-90s",
    name: "Slow Rock Melayu Klasik 90-an",
    iconName: "Guitar",
    genre: "Slow Rock Melayu 90's, Pop Melayu Ballad",
    mood: "Expressive, Heartfelt, Hopeful, Emotional, Elegant, Nostalgic, Soft but Powerful",
    tempo: "72 BPM",
    key: "Am / Em (comfortable male/female range)",
    vocalStyle: "Clear Male Vocal, Emotional, Natural, Clean Pronunciation, Smooth Legato, Soft Vibrato, Chest Voice Dominant",
    lyricLanguage: "Natural Indonesian, Conversational, Simple vocabulary, Heartfelt everyday conversation",
    storyFlow: "Verse 1 (Introduce relationship & hope), Verse 2 (Show misunderstanding & longing), Pre-Chorus (Build tension), Chorus (Main memorable emotional hook), Post-Chorus (Reinforcement), Verse 3 (Show acceptance & commitment), Bridge (Reflection), Final Chorus (Climax), Outro (Fade out peacefully)",
    description: "Gaya klasik Slow Rock Melayu tahun 90-an dengan petikan gitar elektrik, drum lambat berenergi, dan lirik cinta puitis mendalam.",
  },
  {
    id: "pop-melayu-melankolis",
    name: "Pop Melayu Melankolis",
    iconName: "HeartCrack",
    genre: "Pop Melayu Melankolis, Acoustic Ballad, Sad Expressive",
    mood: "Sad, Melancholic, Intimate, Heartbreaking, Tearful, Vulnerable, Tender",
    tempo: "68 BPM",
    key: "Cm / Dm (minor key, highly emotional)",
    vocalStyle: "Vulnerable Male/Female Vocal, Air-y breathing, Soft chest-head voice transition, Emotional sigh, Deep pronunciation",
    lyricLanguage: "Conversational Indonesian, everyday words showing pain, betrayal, or long waiting, highly relatable",
    storyFlow: "Verse 1 (The painful reality), Verse 2 (The memories that remain), Pre-Chorus (Rising sadness), Chorus (Expression of absolute longing & pain), Post-Chorus (Cry of the heart), Verse 3 (Despair but holding on), Bridge (Reflection on the mistakes), Final Chorus (Desperate climax), Outro (Sobs, soft piano fading)",
    description: "Gaya pop Melayu sedih dan intim, dipenuhi instrumen piano lembut, gesekan cello lebar, dan vokal yang rapuh.",
  },
  {
    id: "pop-rock-2000an",
    name: "Pop Rock Indonesia 2000-an",
    iconName: "Music",
    genre: "Pop Rock Indonesia 2000s, Alternative Pop, Classic Band Anthem",
    mood: "Nostalgic, Uplifting, Powerful, Reflective, Anthem, Passionate",
    tempo: "95 BPM",
    key: "G Major / C Major (Bright and accessible)",
    vocalStyle: "Clear Band Vocal, Energetic, Open throat, Wide pitch range, Emotional release in chorus",
    lyricLanguage: "Poetic but simple Indonesian, uplifting metaphors, conversational yet anthemic",
    storyFlow: "Verse 1 (Setting the scene), Verse 2 (Inner thoughts / conflict), Pre-Chorus (Upward momentum), Chorus (Anthemic, easy to sing along), Post-Chorus (Brief pause), Verse 3 (Resolution or moving forward), Bridge (Guitars take lead, peak energy), Final Chorus (Maximum volume/crowd participation), Outro (Rock band finish)",
    description: "Gaya musik band legendaris tahun 2000-an seperti Peterpan, Dewa 19, atau Sheila on 7. Dinamis dengan melodi gitar yang ikonik.",
  },
  {
    id: "balada-pop-akustik",
    name: "Balada Pop Akustik",
    iconName: "Volume2",
    genre: "Acoustic Pop Ballad, Folk-Pop, Pure Intimacy",
    mood: "Intimate, Cozy, Pure, Peaceful, Comforting, Organic",
    tempo: "80 BPM",
    key: "C Major / G Major (Natural acoustic chords)",
    vocalStyle: "Whispery Vocals, Very close to microphone, Dry mix, Natural vibrato, Gentle and intimate",
    lyricLanguage: "Very casual Indonesian, conversational, like whispering to a loved one, comforting",
    storyFlow: "Verse 1 (Simple morning/peaceful moment), Verse 2 (The small details of love), Pre-Chorus (Soft transition), Chorus (Comforting declaration), Post-Chorus (Sweet guitar humming), Verse 3 (Promise for tomorrow), Bridge (Dreamy instrumentation), Final Chorus (Sweetest peak), Outro (Soft acoustic guitar strum fade)",
    description: "Gaya akustik intim dengan petikan gitar kayu organik, gesekan cello lembut, dan vokal yang berbisik dekat di telinga.",
  },
];
